version: 1
policies:
  - id: cf-autotick-bot-test-package-policy
    repo: cf-autotick-bot-test-package-feedstock
    roles:
      - admin
      - maintain
    pull_request: false
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: conda-smithy-feedstock-policy
    repo: conda-smithy-feedstock
    roles:
      - admin
      - maintain
    pull_request: false
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: conda-forge-ci-setup-feedstock-policy
    repo: conda-forge-ci-setup-feedstock
    roles:
      - admin
      - maintain
    pull_request: false
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: pytorch-cpu-feedstock-policy
    repo: pytorch-cpu-feedstock
    roles:
      - admin
      - maintain
      - admin
      - maintain
    pull_request: false
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: libmagma-feedstock-policy
    repo: libmagma-feedstock
    roles:
      - admin
      - maintain
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
access_control:
  - resource: cirun-openstack-gpu-large
    policies:
      - cf-autotick-bot-test-package-policy
      - conda-smithy-feedstock-policy
      - conda-forge-ci-setup-feedstock-policy
      - pytorch-cpu-feedstock-policy
      - libmagma-feedstock-policy
  - resource: cirun-openstack-gpu-xlarge
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-cpu-medium
    policies:
      - cf-autotick-bot-test-package-policy
  - resource: cirun-openstack-cpu-large
    policies:
      - cf-autotick-bot-test-package-policy
