version: 1
policies:
  - id: astra-toolbox-feedstock-policy
    repo: astra-toolbox-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: cf-autotick-bot-test-package-policy
    repo: cf-autotick-bot-test-package-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: clangdev-feedstock-policy
    repo: clangdev-feedstock
    pull_request: true
    roles:
      - admin
      - maintain
      - write
    users:
      - chrisburr
      - h-vetinari
      - isuruf
      - xhochy
  - id: conda-forge-ci-setup-feedstock-policy
    repo: conda-forge-ci-setup-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: false
  - id: conda-smithy-feedstock-policy
    repo: conda-smithy-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: false
  - id: cutlass-feedstock-policy
    repo: cutlass-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: flash-attn-feedstock-policy
    repo: flash-attn-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: gstreamer-feedstock-osx-m4-policy
    repo: gstreamer-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - wolfv
      - hmaarrfk
    pull_request: true
  - id: jaxlib-feedstock-policy
    repo: jaxlib-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: libmagma-feedstock-policy
    repo: libmagma-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: libmagma-feedstock-windows-policy
    repo: libmagma-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - baszalmstra
      - carterbox
      - h-vetinari
      - hmaarrfk
      - isuruf
      - jeongseok-meta
      - mgorny
      - Tobias-Fischer
      - wolfv
    pull_request: true
  - id: llamacpp-feedstock-policy
    repo: llama.cpp-feedstock
    pull_request: true
    roles:
      - admin
      - maintain
      - write
    users:
      - traversaro
  - id: llvmdev-feedstock-policy
    repo: llvmdev-feedstock
    pull_request: true
    roles:
      - admin
      - maintain
      - write
    users:
      - chrisburr
      - h-vetinari
      - isuruf
      - xhochy
  - id: mongodb-feedstock-policy
    repo: mongodb-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: muscat-split-feedstock-policy
    repo: muscat-split-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: nodejs-feedstock-policy
    repo: nodejs-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: onnxruntime-feedstock-policy
    repo: onnxruntime-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: openvino-feedstock-windows-policy
    repo: openvino-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - artanokhov
      - culhatsker
      - mryzhov
      - h-vetinari
    pull_request: true
  - id: pixi-pack-feedstock-osx-m4-policy
    repo: pixi-pack-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - pavelzw
    pull_request: true
  - id: pytorch-cpu-feedstock-cpu-policy
    repo: pytorch-cpu-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - wolfv
      - baszalmstra
      - Tobias-Fischer
      - hmaarrfk
      - h-vetinari
      - isuruf
      - mgorny
      - jeongseok-meta
    pull_request: true
  - id: pytorch-cpu-feedstock-gpu-policy
    repo: pytorch-cpu-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: pytorch-scatter-feedstock-policy
    repo: pytorch_scatter-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: qt-webengine-feedstock-policy
    repo: qt-webengine-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: ray-packages-feedstock-policy
    repo: ray-packages-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: temporalio-cli-feedstock-osx-m4-policy
    repo: temporalio-cli-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - wolfv
    pull_request: true
  - id: tensorflow-feedstock-osx-m4-policy
    repo: tensorflow-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - h-vetinari
      - hmaarrfk
      - wolfv
      - xhochy
      - aktech
      - jaimergp
      - isuruf
    pull_request: true
  - id: tensorflow-feedstock-policy
    repo: tensorflow-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: tinygrad-feedstock-policy
    repo: tinygrad-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - h-vetinari
    pull_request: true
  - id: torchao-feedstock-policy
    repo: torchao-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: viskores-feedstock-policy
    repo: viskores-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: vllm-feedstock-policy
    repo: vllm-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: vtk-m-feedstock-policy
    repo: vtk-m-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: webkit2gtk4.1-feedstock-policy
    repo: webkit2gtk4.1-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
  - id: xformers-feedstock-policy
    repo: xformers-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
access_control:
  # Windows
  - resource: cirun-azure-windows-2xlarge
    policies:
      - clangdev-feedstock-policy
      - libmagma-feedstock-windows-policy
      - llamacpp-feedstock-policy
      - llvmdev-feedstock-policy
      - onnxruntime-feedstock-policy
      - openvino-feedstock-windows-policy
      - pytorch-cpu-feedstock-cpu-policy
      - tinygrad-feedstock-policy
  - resource: cirun-azure-windows-2xlarge-ng
    policies:
      - clangdev-feedstock-policy
      - llvmdev-feedstock-policy
      - pytorch-cpu-feedstock-cpu-policy
  - resource: cirun-azure-windows-4xlarge
    policies:
      - libmagma-feedstock-windows-policy
      - onnxruntime-feedstock-policy
      - pytorch-cpu-feedstock-cpu-policy
      - qt-webengine-feedstock-policy
  - resource: cirun-azure-windows-4xlarge-ng
    policies:
      - pytorch-cpu-feedstock-cpu-policy
  # OSX
  - resource: cirun-macos-m4-large
    policies:
      - gstreamer-feedstock-osx-m4-policy
      - nodejs-feedstock-policy
      - pixi-pack-feedstock-osx-m4-policy
      - pytorch-cpu-feedstock-cpu-policy
      - temporalio-cli-feedstock-osx-m4-policy
      - tensorflow-feedstock-osx-m4-policy
      - tinygrad-feedstock-policy
      - qt-webengine-feedstock-policy
