version: 1
policies:
  - id: cf-autotick-bot-test-package-policy
    repo: cf-autotick-bot-test-package-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: conda-smithy-feedstock-policy
    repo: conda-smithy-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: false
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: conda-forge-ci-setup-feedstock-policy
    repo: conda-forge-ci-setup-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: false
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: libmagma-feedstock-policy
    repo: libmagma-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: pytorch-cpu-feedstock-policy
    repo: pytorch-cpu-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: cutlass-feedstock-policy
    repo: cutlass-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: tensorflow-feedstock-policy
    repo: tensorflow-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: tensorflow-feedstock-osx-m4-policy
    repo: tensorflow-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - h-vetinari
      - hmaarrfk
      - wolfv
      - xhochy
      - aktech
      - jaimergp
      - isuruf
    pull_request: true
  - id: mongodb-feedstock-policy
    repo: mongodb-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: jaxlib-feedstock-policy
    repo: jaxlib-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: xformers-feedstock-policy
    repo: xformers-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: pytorch-cpu-feedstock-windows-policy
    repo: pytorch-cpu-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - wolfv
      - baszalmstra
      - Tobias-Fischer
      - hmaarrfk
      - h-vetinari
      - isuruf
      - mgorny
      - jeongseok-meta
    pull_request: true
  - id: libmagma-feedstock-windows-policy
    repo: libmagma-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - baszalmstra
      - carterbox
      - h-vetinari
      - hmaarrfk
      - isuruf
      - jeongseok-meta
      - mgorny
      - Tobias-Fischer
      - wolfv
    pull_request: true
  - id: nodejs-feedstock-policy
    repo: nodejs-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: flash-attn-feedstock-policy
    repo: flash-attn-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: onnxruntime-feedstock-windows-policy
    repo: onnxruntime-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: temporalio-cli-feedstock-osx-m4-policy
    repo: temporalio-cli-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - wolfv
    pull_request: true
  - id: ray-packages-feedstock-policy
    repo: ray-packages-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: pixi-pack-feedstock-osx-m4-policy
    repo: pixi-pack-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - pavelzw
    pull_request: true
  - id: gstreamer-feedstock-osx-m4-policy
    repo: gstreamer-feedstock
    roles:
      - admin
      - maintain
      - write
    users:
      - wolfv
      - hmaarrfk
    pull_request: true
  - id: vtk-m-feedstock-policy
    repo: vtk-m-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: muscat-split-feedstock-policy
    repo: muscat-split-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: astra-toolbox-feedstock-policy
    repo: astra-toolbox-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
  - id: vllm-feedstock-policy
    repo: vllm-feedstock
    roles:
      - admin
      - maintain
      - write
    pull_request: true
    users_from_json: https://raw.githubusercontent.com/Quansight/open-gpu-server/main/access/conda-forge-users.json
access_control:
  - resource: cirun-openstack-gpu-large
    policies:
      - cf-autotick-bot-test-package-policy
      - conda-smithy-feedstock-policy
      - conda-forge-ci-setup-feedstock-policy
      - libmagma-feedstock-policy
      - pytorch-cpu-feedstock-policy
      - flash-attn-feedstock-policy
      - tensorflow-feedstock-policy
      - muscat-split-feedstock-policy
      - astra-toolbox-feedstock-policy
  - resource: cirun-openstack-gpu-xlarge
    policies:
      - cf-autotick-bot-test-package-policy
      - pytorch-cpu-feedstock-policy
      - tensorflow-feedstock-policy
  - resource: cirun-openstack-cpu-medium
    policies:
      - cf-autotick-bot-test-package-policy
      - onnxruntime-feedstock-windows-policy
  - resource: cirun-openstack-cpu-large
    policies:
      - cf-autotick-bot-test-package-policy
      - pytorch-cpu-feedstock-policy
      - cutlass-feedstock-policy
      - tensorflow-feedstock-policy
      - mongodb-feedstock-policy
      - jaxlib-feedstock-policy
      - nodejs-feedstock-policy
      - flash-attn-feedstock-policy
      - onnxruntime-feedstock-windows-policy
      - vllm-feedstock-policy
  - resource: cirun-openstack-gpu-2xlarge
    policies:
      - cf-autotick-bot-test-package-policy
      - pytorch-cpu-feedstock-policy
      - tensorflow-feedstock-policy
      - vllm-feedstock-policy
  - resource: cirun-openstack-gpu-4xlarge
    policies:
      - cf-autotick-bot-test-package-policy
      - pytorch-cpu-feedstock-policy
  - resource: cirun-openstack-cpu-2xlarge
    policies:
      - cf-autotick-bot-test-package-policy
      - jaxlib-feedstock-policy
      - tensorflow-feedstock-policy
      - vtk-m-feedstock-policy
      - vllm-feedstock-policy
  - resource: cirun-openstack-cpu-4xlarge
    policies:
      - cf-autotick-bot-test-package-policy
      - tensorflow-feedstock-policy
      - ray-packages-feedstock-policy
      - vllm-feedstock-policy
  - resource: cirun-openstack-cpu-xlarge
    policies:
      - cf-autotick-bot-test-package-policy
      - tensorflow-feedstock-policy
      - xformers-feedstock-policy
      - mongodb-feedstock-policy
      - flash-attn-feedstock-policy
      - onnxruntime-feedstock-windows-policy
      - vllm-feedstock-policy
  - resource: cirun-azure-windows-2xlarge
    policies:
      - pytorch-cpu-feedstock-windows-policy
      - libmagma-feedstock-windows-policy
      - onnxruntime-feedstock-windows-policy
  - resource: cirun-azure-windows-4xlarge
    policies:
      - pytorch-cpu-feedstock-windows-policy
      - libmagma-feedstock-windows-policy
      - onnxruntime-feedstock-windows-policy
  - resource: cirun-macos-m4-large
    policies:
      - tensorflow-feedstock-osx-m4-policy
      - temporalio-cli-feedstock-osx-m4-policy
      - pixi-pack-feedstock-osx-m4-policy
      - gstreamer-feedstock-osx-m4-policy
