# Self-Hosted Github Action Runners via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: cirun-azure-windows-2xlarge
    cloud: azure
    # 8 cores, 32GB Ram, 300GB storage, x64
    instance_type: Standard_D8ads_v5
    machine_image: "/subscriptions/df033e15-d7e5-43a0-88b8-95b833d272f9/resourceGroups/cirun-runner-images-via-packer/providers/Microsoft.Compute/images/cirun-win22-dev"
    region: uksouth
    labels:
      - windows
      - x64
      - cirun-azure-windows-2xlarge
    extra_config:
      licenseType: Windows_Server

  - name: cirun-azure-windows-4xlarge
    cloud: azure
    # 16 cores, 64GB Ram, 1000GB storage, x64
    instance_type: Standard_D16ads_v5
    machine_image: "/subscriptions/df033e15-d7e5-43a0-88b8-95b833d272f9/resourceGroups/cirun-runner-images-via-packer/providers/Microsoft.Compute/images/cirun-win22-dev"
    region: uksouth
    labels:
      - windows
      - x64
      - cirun-azure-windows-4xlarge
    extra_config:
      licenseType: Windows_Server
      storageProfile:
        osDisk:
          diskSizeGB: 1000

  # for debugging new images after https://github.com/conda-forge/.cirun/pull/145
  - name: cirun-azure-windows-2xlarge-ng
    cloud: azure
    # 8 cores, 32GB Ram, 300GB storage, x64
    instance_type: Standard_D8ads_v5
    machine_image: "/subscriptions/df033e15-d7e5-43a0-88b8-95b833d272f9/resourceGroups/cirun-runner-images-20260409-051231/providers/Microsoft.Compute/images/cirun-win22-20260409-051231"
    region: uksouth
    labels:
      - windows
      - x64
      - cirun-azure-windows-2xlarge-ng
    extra_config:
      licenseType: Windows_Server

  - name: cirun-azure-windows-4xlarge-ng
    cloud: azure
    # 16 cores, 64GB Ram, 1000GB storage, x64
    instance_type: Standard_D16ads_v5
    machine_image: "/subscriptions/df033e15-d7e5-43a0-88b8-95b833d272f9/resourceGroups/cirun-runner-images-20260409-051231/providers/Microsoft.Compute/images/cirun-win22-20260409-051231"
    region: uksouth
    labels:
      - windows
      - x64
      - cirun-azure-windows-4xlarge-ng
    extra_config:
      licenseType: Windows_Server
      storageProfile:
        osDisk:
          diskSizeGB: 1000

  - name: cirun-macos-m4-large
    cloud: on_prem
    # 8 cores, 8GB Ram, 100GB storage, M4
    instance_type: 8vcpu-8gb-100gb
    machine_image: "cirunlabs/macos-sequoia-xcode:16.4"
    region: RegionOne
    labels:
      - macOS
      - arm64
      - cirun-macos-m4-large
