# Self-Hosted Github Action Runners on Openstack via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: cirun-openstack-gpu-large
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: gpu_large
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-nvidia-20230914
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-gpu-large

  - name: cirun-openstack-gpu-xlarge
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: gpu_xlarge
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-nvidia-20230914
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-gpu-xlarge

  - name: cirun-openstack-gpu-2xlarge
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: gpu_2xlarge
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-nvidia-20230914
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-gpu-2xlarge

  - name: cirun-openstack-gpu-4xlarge
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: gpu_4xlarge
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-nvidia-20230914
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-gpu-4xlarge

  - name: cirun-openstack-cpu-medium
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: ci_medium
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-20231018
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-cpu-medium

  - name: cirun-openstack-cpu-large
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: ci_large
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-20231018
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-cpu-large

  - name: cirun-openstack-cpu-xlarge
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: ci_xlarge
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-20231018
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-cpu-xlarge

  - name: cirun-openstack-cpu-2xlarge
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: ci_2xlarge
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-20231018
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-cpu-2xlarge

  - name: cirun-openstack-cpu-4xlarge
    # Cloud Provider: Openstack
    cloud: openstack
    # Instance type refers to flavors in openstack
    instance_type: ci_4xlarge
    # The machine image to use for creating VM
    machine_image: ubuntu-2204-20231018
    region: RegionOne
    labels:
      - linux
      - x64
      - cirun-openstack-cpu-4xlarge

  - name: cirun-azure-windows-2xlarge
    cloud: azure
    # 8 cores, 32GB Ram, x64
    instance_type: Standard_D8s_v3
    machine_image: "/subscriptions/df033e15-d7e5-43a0-88b8-95b833d272f9/resourceGroups/cirun-runner-images-via-packer/providers/Microsoft.Compute/images/cirun-win22-dev"
    region: uksouth
    labels:
      - windows
      - cirun-azure-windows-2xlarge
    extra_config:
      licenseType: Windows_Server